name:                halgrep
version:             0.1.0.0
github:              "reggiemcdonald/halgrep"
license:             MIT
author:              "Kyle Da Silva, Julian Mentasti, Reg McDonald"
# maintainer:          "example@example.com"
# copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Full-text search put to its fullest possible use

dependencies:
- base >= 4.7 && < 5
- directory
- unix

library:
  source-dirs: src

executables:
  halgrep-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - halgrep

tests:
  halgrep-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - halgrep
